### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by arcreigh** [devgianlu/PYX-Reloaded#106]
I am looking forward to seeing the game working! I had no issues setting this up and getting nginx in front of it was a breeze. Is there a semi working version of the game itself? or is this all just web gui stuff today?

**Comment by HopperMCS** [comment]
The game works! Add some friends and jump into a session! Gianluca stated he was done with development. Due to some new techniques I've learned, I'm considering a re-write in another language within the next month or so. On Dec 8, 2018 11:58 PM, arcreigh <notifications@github.com> wrote:I am looking forward to seeing the game working! I had no issues setting this up and getting nginx in front of it was a breeze. Is there a semi working version of the game itself? or is this all just web gui stuff today?

**Comment by arcreigh** [comment]
Hmmm... I must have missed something in my config than, The game refuses to start for me even with three clients on, cah.playtfg.com is the site, I have an nginx reverse proxy running in front of the physical server.

**Comment by HopperMCS** [comment]
I don't remember the exact setup details, I remember there was a config thing along with the card contents, but I could be wrong. It's been a year since I worked on this project, and @devgianlu stated he was done working on it. 

I fell off the coding bandwagon, so I'm working on personal solo projects to get back in the loop of things.

**Comment by arcreigh** [comment]
Hmmm do you happen to have discord/some free time? If so I would love to assist in some documentation to finalize this project. As it stands today the readme states that the game itself is unplayable.

**Comment by HopperMCS** [comment]
We have a server, here's the link for all interested parties:https://discord.gg/hu852hFollowing the shutdown of the original PYX site, my friends and I have been considering setting up an instance on a DigitalOcean droplet. I'll be working on a cleanroomed version of this project written in a single language for both front and backend probably around the second half of this month. On Dec 9, 2018 12:50 AM, arcreigh <notifications@github.com> wrote:Hmmm do you happen to have discord/some free time? If so I would love to assist in some documentation to finalize this project.

**Comment by HopperMCS** [comment]
That last one was sent through my mail client, sorry for formatting issues. Make sure you have at least two people in the game. It is playable, I just never got around to fixing that readme. @arcreigh, this is really worth your time to set up. It is mobile-friendly, and there's some cool design changes that the original never had. 

I want to note that because I didn't understand the backend (Java isn't my language, and tbh it probably never will be) and only had two or three weeks of free time to contribute to front-end (and not fully understanding how to attach the two pieces), @devgianlu is responsible for just how much of a beast this fork of the original project is, and I have to give him credit for the vast amount of work he did to turn the original PYX from an archaic CAH clone to the modern version that can be played through this project.  

I think it probably holds up about a year after development stopped. Everything I imagined for this project came to fruition.

**Comment by devgianlu** [comment]
This project isn't dead. I've stopped working on it because to me it was pretty much done. I can keep developing if necessary. 

The web interface isn't the best thing on Earth as I'm not a web developer, but the server side is very solid. 

I'll look at your issue ASAP.

**Comment by devgianlu** [comment]
@arcreigh I've just tried playing a game and it works fine. Could you provide some additional feedback?

**Comment by arcreigh** [comment]
Please look at cah-new.playtfg.com I am not seeing any notifications from the server that a new user has joined my game. I am also unable to start the game,

My process for building was from the clone

mvn clean package.

I would than copy the deploy.zip to another directory and than unzip it.
sudo java -jar PYX-Reloaded.jar

I am running java 1.8.0 with nginx in front of everything.
internally everything works I believe I may have screwed up something in my proxy. see below. 

```
server {
  listen 80;
  server_name cah-new.playtfg.com;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl http2;
  ssl_certificate /etc/ssl/certs/playtfg-fullchain.pem;
  ssl_certificate_key /etc/ssl/private/playtfg-key.pem;
  include /etc/nginx/snippets/ssl.conf;
  server_name cah-new.playtfg.com;
  access_log /var/log/cah-new_playtfg_access.log;
  error_log /var/log/cah-new_playtfg_error.log;
  location / {
    proxy_set_header host cah-new.playtfg.com;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass http://10.26.0.120/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect http://10.26.0.120/ https://cah-new.playtfg.com/;
    client_max_body_size 10m;
  }
}
```

**Comment by devgianlu** [comment]
See https://github.com/devgianlu/PYX-Reloaded/issues/104#issuecomment-387533326.

**Comment by arcreigh** [comment]
Just found that, gah got it up and working now! I would like if you closed out of one game it wouldn't take you to the login though! maybe that is something else I am missing?

**Comment by devgianlu** [comment]
Just tried this on your server, but I couldn't reproduce it.

**Comment by arcreigh** [comment]
hmm that may have been vpn related my apologies!
