### ISSUE TITLE
Add Cardcast to the "New Game" Dialog

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#12]
Get rid of the command. Add the ability to enter Cardcast decks into the "New Game" dialog instead of the current /command setup. For better usability/visibility of the feature to newcomers.

**Comment by MGageMorgan** [comment]
See #23.

I really liked that functionality in the app and think Web should have something like it along with the ability to enter codes in manually. All selected codes, whether it be manual or through the browse (sub?)-dialog, should appear in the "Decks" list you've wireframed inside the "Cardcast" box.

**Comment by devgianlu** [comment]
Implemented with 5666d1d6b5a9e696e3eb6fd99db846cbbb7a9d8e and 06e97c509e8c543cfe6a1e10f5ec0936f35d6fa4. Not closing due to space for improvements in the layout. https://github.com/devgianlu/PYX-Reloaded/blob/b5e454fa9cbc1e1336d2fe0a882fd0019bc04c87/WebContent/lobbies.html#L197
https://github.com/devgianlu/PYX-Reloaded/blob/b5e454fa9cbc1e1336d2fe0a882fd0019bc04c87/WebContent/js/new_game.js#L230

@MGageMorgan

**Comment by MGageMorgan** [comment]
@devgianlu,

Will fix when I get a chance. I need to study at least two hours worth of content in each class, and math is a BITCH. But hey, good work getting it in a working state!
