### ISSUE TITLE
Like/dislike game

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#17]
Give users possibility to like or dislike games.

**Comment by MGageMorgan** [comment]
@devgianlu Because games are temporary, are we going to have some sort of mechanism to watch replays and then like/dislike? I know my friends and I only play a couple hours at a time.

**Comment by devgianlu** [comment]
We definitely could add replay functionality. That would be fun. We could also add a leaderboad with the replays of the most liked games.

**Comment by MGageMorgan** [comment]
@devgianlu Yeah, I like this and the replays idea. However, we should probably focus on feature parity between this and the original. After we reach feature parity, we begin working on the uncharted territory stuff. That will be fun, but we have to keep focus. The good news is that the issue tracker keeps discussions like this so that when we go to implement this stuff, it will be there laid out for us.

**Comment by devgianlu** [comment]
@MGageMorgan Merged with an issue: the dropdowns for the likes/dislikes number don't work.
